### ISSUE TITLE
got an error

### ISSUE THREAD

**Issue by haha010508** [etzinis/unsup_speech_enh_adaptation#2]
unsup_speech_enh_adaptation/baseline/models/improved_sudormrf.py(226)forward()
    225             resampled_out_k = self.upsampler(output.pop(-1))
    226             output[-1] = output[-1] + resampled_out_k
    227

ipdb> resampled_out_k.shape
torch.Size([1, 512, 690])
ipdb>  output[-1].shape
torch.Size([1, 512, 689])
ipdb>  output[-1].shape

so, the size is not match, so got an error!

**Comment by etzinis** [comment]
Oh sorry about that, this is about wrong padding, I am workin on it right now

Could you please share with me the model parameters and the shape of the tensor that caused this ?

**Comment by etzinis** [comment]
Cool, just fixed that in 4059664d90b712ec3ba082bd56a3b0ea40de7899 
Thanks for mentioning that!
