### ISSUE TITLE
Chime dataset link is wrong

### ISSUE THREAD

**Issue by rimiyeyo** [etzinis/unsup_speech_enh_adaptation#3]
Hi I tried your github code. but I had some error message.
but I coundn't solve error message.
I think Chime dataset link is something wrong.
Maybe, Chime dataset github link updated.
The json_files of the chime dataset has a dev folder and a train folder, but no eval folder.
if you try to 'run_models_on_chime.ipynb', you can get error message.
plz check your github datset thanks!

and got bless you.

**Comment by etzinis** [comment]
Hey, probably I will think about removing this notebook since it is not actually very useful for anyone, it was just meant to be as a debug tool. The CHiME dataset generation is not actually so relevant with this repo.

Have a great day!
